apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edam.fullname" . }}-secret
  labels:
    {{- include "edam.labels" . | nindent 4 }}
type: Opaque
data:
  # 以下是占位值，生产环境必须修改
  # 使用 `helm install --set secret.dbPassword=xxx` 覆盖
  db-password: {{ .Values.secret.dbPassword | b64enc | quote }}
  vault-token: {{ .Values.secret.vaultToken | b64enc | quote }}
  jwt-secret: {{ .Values.secret.jwtSecret | b64enc | quote }}