{{- if .Values.backend.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "edam.fullname" . }}-backend
  labels:
    {{- include "edam.labels" . | nindent 4 }}
    release: prometheus
spec:
  selector:
    matchLabels:
      {{- include "edam.backend.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.backend.serviceMonitor.path }}
      interval: {{ .Values.backend.serviceMonitor.interval }}
{{- end }}